import React, { useMemo, useState } from "react";
import { Flex, Grid } from "@dynatrace/strato-components/layouts";
import { Text } from "@dynatrace/strato-components/typography";
import { Button } from "@dynatrace/strato-components/buttons";
import Colors from "@dynatrace/strato-design-tokens/colors";
import { documentsClient } from "@dynatrace-sdk/client-document";
import { openDocument } from "@dynatrace-sdk/navigation";
import { SectionCard, StatusPill } from "../components/SectionCard";
import { ChoiceCard } from "../components/ChoiceCard";
import { CodeBlock } from "../components/CodeBlock";
import { ResultBanner } from "../components/ResultBanner";
import { Callout } from "../components/Callout";
import { KpiCard } from "../components/KpiCard";
import { TextField } from "../components/Field";
import { useSelection } from "../context/SelectionContext";
import { useCreateAction } from "../hooks/useCreateAction";
import { useSlos } from "../hooks/useSlos";
import { ENTITY_TYPE_BY_KEY } from "../constants/entityTypes";
import { DASHBOARD_TEMPLATES, buildValetDashboard } from "../utils/dashboard";

export const DashboardPanel: React.FC<{ startStep: number }> = ({ startStep }) => {
  const { selected, selectedTypeKeys } = useSelection();
  const singleType = selectedTypeKeys.length === 1 ? selectedTypeKeys[0] : null;
  const meta = singleType ? ENTITY_TYPE_BY_KEY.get(singleType) : undefined;

  const [templateKey, setTemplateKey] = useState<string | null>(null);
  const [title, setTitle] = useState("");
  // SLOs bound to the dashboard — each becomes two tiles running the SLO's own SLI.
  const { slos, isLoading: slosLoading, error: slosError } = useSlos();
  const [sloIds, setSloIds] = useState<Set<string>>(() => new Set());
  const toggleSlo = (id: string) =>
    setSloIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  const boundSlos = slos.filter((s) => sloIds.has(s.id) && s.indicator);
  const [createdId, setCreatedId] = useState<string | null>(null);

  const templates = DASHBOARD_TEMPLATES.map((t) => ({
    template: t,
    applies: !!singleType && t.appliesTo.includes(singleType),
  }));
  const template = templates.find((t) => t.template.key === templateKey && t.applies)?.template;

  const effectiveTitle =
    title || `${template?.label ?? "SLO"} — ${selected.length} ${meta?.label ?? "entities"}`;

  const doc = useMemo(() => {
    if (!template || !singleType) return null;
    return buildValetDashboard({
      entities: selected,
      typeKey: singleType,
      typeLabel: meta?.label ?? singleType,
      title: effectiveTitle,
      slos: boundSlos.map((s) => ({ name: s.name, target: s.target, indicator: s.indicator! })),
    });
  }, [template, singleType, selected, meta, effectiveTitle, boundSlos.map((s) => s.id).join(",")]);

  const tileCount = doc ? Object.keys(doc.tiles).length : 0;
  const scanning = doc
    ? Object.values(doc.tiles).filter((t) => t.query?.startsWith("fetch ")).length
    : 0;

  const { busy, result, execute: create } = useCreateAction({
    run: async () => {
      const res = await documentsClient.createDocument({
        body: {
          name: effectiveTitle,
          type: "dashboard",
          description: `Generated by Monitoring Assist — ${template?.label} for ${selected.length} ${meta?.label ?? "entities"}.`,
          content: new Blob([JSON.stringify(doc)], { type: "application/json" }),
        },
      });
      const id = (res as { id?: string })?.id ?? null;
      setCreatedId(id);
      return id;
    },
    successTitle: "Dashboard created",
    failureTitle: "Failed to create the dashboard",
    describe: (id) =>
      `“${effectiveTitle}” with ${tileCount} tiles.${id ? ` Id: ${id}.` : ""} Open it from the Dashboards app or the button below.`,
  });

  if (!singleType) {
    return (
      <SectionCard step={startStep} title="Pick a template">
        <Text textStyle="small" style={{ color: Colors.Text.Warning.Default }}>
          A dashboard is built around one entity type. Keep only one type in your selection above.
        </Text>
      </SectionCard>
    );
  }

  return (
    <>
      <SectionCard
        step={startStep}
        title="Pick a template"
        subtitle="Each template is a layout with the queries already written and validated."
        aside={template ? <StatusPill tone="ok">{template.label}</StatusPill> : <StatusPill tone="warn">Choose one</StatusPill>}
      >
        <Grid gridTemplateColumns="repeat(auto-fit, minmax(300px, 1fr))" gap={8}>
          {templates.map(({ template: t, applies }) => (
            <ChoiceCard
              key={t.key}
              selected={t.key === templateKey}
              disabled={!applies}
              title_={!applies ? `${t.label} doesn't apply to ${meta?.label ?? "this type"}` : undefined}
              title={t.label}
              description={`${t.description} — ${t.source}`}
              onClick={() => setTemplateKey(t.key)}
            />
          ))}
        </Grid>
      </SectionCard>

      {template && doc && (
        <SectionCard
          step={startStep + 1}
          title="Name it"
          aside={<StatusPill tone="neutral">{tileCount} tiles</StatusPill>}
        >
          <Flex flexDirection="column" gap={16}>
            <Flex gap={12} flexWrap="wrap">
              <KpiCard
                label="Tiles"
                value={tileCount}
                subLabel={boundSlos.length ? `VALET + ${boundSlos.length} SLO${boundSlos.length === 1 ? "" : "s"}` : "header, 5 headline values, 5 charts"}
              />
              <KpiCard
                label="Metric tiles"
                value={tileCount - scanning - 1}
                subLabel="0 bytes scanned"
                colorVariant="positive"
              />
              <KpiCard
                label="Scanning tiles"
                value={scanning}
                subLabel="Davis problems — the “Tickets” proxy"
                colorVariant="warning"
              />
            </Flex>
            <Grid gridTemplateColumns="repeat(auto-fit, minmax(240px, 1fr))" gap={16}>
              <TextField label="Dashboard name" value={title} onChange={setTitle} placeholder={effectiveTitle} />
            </Grid>

            <Flex flexDirection="column" gap={8}>
              <Text textStyle="base-emphasized">Bind SLOs to this dashboard</Text>
              <Text textStyle="small" style={{ color: Colors.Text.Neutral.Subdued }}>
                Each one becomes two tiles — current value and timeline — running the SLI query stored
                in the SLO, so the dashboard and the SLO app can never disagree.
              </Text>
              {slosError ? (
                <Text textStyle="small" style={{ color: Colors.Text.Critical.Default }}>Couldn't list SLOs: {slosError}</Text>
              ) : slosLoading ? (
                <Text textStyle="small" style={{ color: Colors.Text.Neutral.Subdued }}>Loading SLOs…</Text>
              ) : slos.length === 0 ? (
                <Text textStyle="small" style={{ color: Colors.Text.Neutral.Subdued }}>
                  No SLOs in this environment yet — create some with the SLO action first.
                </Text>
              ) : (
                <Grid gridTemplateColumns="repeat(auto-fit, minmax(260px, 1fr))" gap={8}>
                  {slos.map((s) => (
                    <ChoiceCard
                      key={s.id}
                      multi
                      selected={sloIds.has(s.id)}
                      disabled={!s.indicator}
                      title_={!s.indicator ? "This SLO has no custom SLI query to plot" : undefined}
                      title={s.name}
                      description={s.target !== undefined ? `target ${s.target}%` : "no target"}
                      onClick={() => toggleSlo(s.id)}
                    />
                  ))}
                </Grid>
              )}
            </Flex>
            <Callout tone="info">
              <strong>Tickets are Davis problems.</strong> Dynatrace has no ticket system, so the T
              in VALET shows the problems that affected these entities — the nearest honest proxy.
              Those two tiles read <code>dt.davis.problems</code> and are the only ones that scan
              data; everything else is metric-based.
            </Callout>
          </Flex>
        </SectionCard>
      )}

      {template && doc && (
        <SectionCard
          step={startStep + 2}
          title="Create the dashboard"
          subtitle="Written through the Document API as a dashboard you own; edit it freely afterwards."
          aside={createdId ? <StatusPill tone="ok">Created</StatusPill> : <StatusPill tone="ok">Ready</StatusPill>}
        >
          <Flex flexDirection="column" gap={12}>
            <ResultBanner result={result} />
            <CodeBlock label="Dashboard document" collapsible code={JSON.stringify(doc, null, 2)} />
            <Flex gap={12} flexWrap="wrap">
              <Button variant="accent" color="primary" onClick={create} disabled={busy}>
                {busy ? "Creating…" : "Create dashboard"}
              </Button>
              {createdId && (
                <Button variant="default" onClick={() => openDocument(createdId)}>
                  Open dashboard
                </Button>
              )}
            </Flex>
          </Flex>
        </SectionCard>
      )}
    </>
  );
};
